"""
`GlobalBaseParams` contain the global parameters (simulated timespan `t_max`, nutrient influx rate `Xdot_in`, etc.)
"""
@with_kw mutable struct GlobalBaseParams <: AbstractParams
    t_max::Float64 = 21. # maximum simulation time (d)
    Xdot_in::Float64 = 1200. # set to be a little above the absolute maximum ingestion rate according to default DEBBaseParams
    V_patch::Float64 = 0.05 # volume of a patch (L) (or the entire similated environment)
    C_W::Vector{Float64} = [0.] # external chemical concentrations
    units::NamedTuple = (time = "d", mass = "mug C", volume = "L")
end

"""
<<<<<<< HEAD
DEBBase Parameters. \\
Default values are for Daphnia magna and Azoxystrobin.
=======
`DEBBaseParams` contain DEB and TKTD parameters. Default values are for Daphnia magna and Azoxystrobin in μg C. <br>
DEBBase.jl uses a hierarchical modelling approach where the `DEBBaseParams` are  parameters which are common across all agents of a species. <br>
Variability is given by the zoom factor `Z::Distribution`, which is always applied to the surface-area specific ingestion rates 
and can optionally propagate to parameters indicated in `propagate_zoom::NTuple`. <br>
`Z` is `Dirac(1)` by default, i.e. there is no agent variability in the default parameters. <br>
The agent-specific parameters are generated by `simulator` and given by `pown::ComponentArray`.
>>>>>>> feature-IBM
"""
@with_kw mutable struct DEBBaseParams <: AbstractParams
    Z::Distribution = Dirac(1.) # agent variability is accounted for in the zoom factor. This can be set to a Dirac distribution if a zoom factor should be applied without introducing agent variability.
    propagate_zoom::@NamedTuple{X_emb_int::Bool, H_p::Bool, K_X::Bool} = (X_emb_int = true, H_p = true, K_X = true) # Parameters to which Z will be propagated. Z is *always* applied to `Idot_max_rel` (with appropriate scaling).
    X_emb_int::Float64 = 19.42 # initial vitellus mass
    K_X::Float64 = 1. # Population mean of half-saturation constant for food uptake
    Idot_max_rel::Float64 = 22.9 # agent maximum size-specific ingestion rate
    Idot_max_rel_emb_mean::Float64 = 22.9 # Population mean of the size-specific embryonic ingestion rate
    Idot_max_rel_emb::Float64 = 22.9 # agent size-specific embryonic ingestion rate
    kappa::Float64 = 0.539 # Somatic allocation fraction
    eta_IA::Float64 = 0.33 # Assimilation efficiency
    eta_AS::Float64 = 0.8 # Growth efficiency
    eta_SA::Float64 = 0.8 # Shrinking efficiency
    eta_AR::Float64 = 0.95 # Reproduction efficiency
    k_M::Float64 = 0.59 # Somatic maintenance rate constant
    k_J::Float64 = 0.504 # Maturity maintenance rate constant
    H_p::Float64 = 100. # agent maturity at puberty
    
    k_D_G::Vector{Float64} = [0.] # Dominant rate constants | PMoA growth efficiency
    k_D_M::Vector{Float64} = [0.] # Dominant rate constants | PMoA maintenance costs
    k_D_A::Vector{Float64} = [0.] # Dominant rate constants | PMoA assimilation efficiency
    k_D_R::Vector{Float64} = [0.38] # Dominant rate constants | PMoA reproduction efficiency
    k_D_h::Vector{Float64} = [0.] # Dominant rate constants | PMoA hazard rate
    
    drc_functs_G::Vector{Function} = [LL2] # Dose-response functions | PMoA growth efficiency
    drc_functs_M::Vector{Function} = [LL2M] # Dose-response functions | PMoA maintenance costs
    drc_functs_A::Vector{Function} = [LL2] # Dose-response functions | PMoA assimilation efficiency
    drc_functs_R::Vector{Function} = [LL2] # Dose-response functions | PMoA reproduction efficiency
    drc_functs_h::Vector{Function} = [LL2h] # Dose-response functions | PMoA hazard rate

    drc_params_G::Vector{NTuple} = [(1e10, 1e10)] # Dose-response parameters | PMoA growth efficiency
    drc_params_M::Vector{NTuple} = [(1e10, 1e10)] # Dose-response parameters | PMoA maintenance costs
    drc_params_A::Vector{NTuple} = [(1e10, 1e10)] # Dose-response parameters | assimilation efficiency
    drc_params_R::Vector{NTuple} = [(167., 0.93)] # Dose-response parameters | PMoA reproduction efficiency
    drc_params_h::Vector{NTuple} = [(1e10, 1e10)] # Dose-response parameters | PMoA hazard rate
end

"""
A `BaseParamCollection` contains global parameters `glb` and DEB parameters `deb` (including TKTD-parameters). <br>
Initialize the default parameter collection with `BaseParamCollection()`.
"""
@with_kw mutable struct BaseParamCollection <: AbstractParamCollection
    glb::AbstractParams = GlobalBaseParams()
    deb::AbstractParams = DEBBaseParams()
end



