name: Documentation

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.10.4'

      - name: Install dependencies
        run: julia --project=docs -e 'using Pkg; Pkg.instantiate()'

      - name: Build documentation
        run: julia --project=docs docs/make.jl

      - name: Deploy documentation
        run: |
          julia --project=docs -e '
            using Documenter;
            include("docs/make.jl");
            deploydocs(repo="github.com/SimonHansul/DEBBase.jl.git")'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
